JP_FOOD ={
    'style': 'japanese',
    'style_check':[
        'japan',
        'sushi',
        'ramen',
        'katsu',
        'miso',
        'soba',
        'edamame',
        'teriyaki',
        'yakitori',
        'wasabi',
        'gyoza',
        'mochi',
        'tempura',
        'tamago',
        'sukiyaki',
        'hiyayakko',
        'sake',
        'onito shavings',
        'mirin',
        'dashi',
        'matcha'
    ],
    'change_dict':{
        'noodle': ['ramen', 'soba'],
        'rice': ['sushi rice'],
        'mustard': ['wasabi'],
        'mayonnaise': ['japanese mayonnaise'],
        'sauce': ['japanese soy sauce'],
        'wine': ['sake'],
        'broth': ['dashi'],
        'tea powder': ['matcha green tea powder'],
        'tea leaves': ['matcha green tea powder'],
        'tea': ['matcha green tea']
    },
    'add_item_method': ['mix', 'stir', 'blend', 'combine'],
    'add_item_ingred':[
        ['1/4', 'cup', 'miso paste'],
        ['1', 'pinch', 'onito shavings (dry fish flakes)'],
        ['1', 'tablespoons', 'mirin (japanese sweet wine)']
    ],
    'primary_methods': ['broil', 'boil', 'fry', 'simmer', 'grill', 'bake'],
} 
